### Add a new product
POST http://localhost:3000/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo1LCJuYW1lIjoiYWRtaW4iLCJhZGRyZXNzIjoibm9uZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzNTEwNDMxLCJleHAiOjE3MTM1OTY4MzF9.8MCwZM1tSoXTtVeg1hjEXYrNQKd4ciXq2zQuVuwpyLg
Content-Type: application/json

{
  "name": "Test Food",
  "description": "This is a test food",
  "price": 19.99,
  "image": "test.jpg",
  "categoryId": 1
}

### List all products
GET http://localhost:3000/api/v1/products

### Get a product by id
GET http://localhost:3000/api/v1/products/2

### Update a product
PUT http://localhost:3000/api/v1/products/2
Content-Type: application/json

{
  "name": "Test Food Updated",
  "description": "This is a test food updated",
  "price": 20.99,
  "category": "Test Category Updated",
  "image": "testUpdate.jpg"
}

### Delete a product
DELETE http://localhost:3000/api/v1/products/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo1LCJuYW1lIjoiYWRtaW4iLCJhZGRyZXNzIjoibm9uZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzNTEwNDMxLCJleHAiOjE3MTM1OTY4MzF9.8MCwZM1tSoXTtVeg1hjEXYrNQKd4ciXq2zQuVuwpyLg





### Add a new customer
POST http://localhost:3000/api/v1/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo1LCJuYW1lIjoiYWRtaW4iLCJhZGRyZXNzIjoibm9uZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzNTEwNDMxLCJleHAiOjE3MTM1OTY4MzF9.8MCwZM1tSoXTtVeg1hjEXYrNQKd4ciXq2zQuVuwpyLg
Content-Type: application/json

{
  "name": "Patrik",
  "address": "none",
  "email": "patrik@gmail.com",
  "password": "123",
  "role": "user"
}

### List all customers
GET http://localhost:3000/api/v1/customers


### Get a customer by id
GET http://localhost:3000/api/v1/customers/1

### Modify a customer
PUT http://localhost:3000/api/v1/customers/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo1LCJuYW1lIjoiYWRtaW4iLCJhZGRyZXNzIjoibm9uZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzNTEwNDMxLCJleHAiOjE3MTM1OTY4MzF9.8MCwZM1tSoXTtVeg1hjEXYrNQKd4ciXq2zQuVuwpyLg
Content-Type: application/json

{
  "name": "Patrik",
  "address": "Helsinki katu 2",
  "email": "patrik@gmail.com",
  "password": "123",
  "role": "user"
}

### Delete a customer
DELETE http://localhost:3000/api/v1/customers/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo1LCJuYW1lIjoiYWRtaW4iLCJhZGRyZXNzIjoibm9uZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzNTEwNDMxLCJleHAiOjE3MTM1OTY4MzF9.8MCwZM1tSoXTtVeg1hjEXYrNQKd4ciXq2zQuVuwpyLg

### Post login
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "name": "admin",
  "password": "admin123"
}

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo1LCJuYW1lIjoiYWRtaW4iLCJhZGRyZXNzIjoibm9uZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzNTEwNDMxLCJleHAiOjE3MTM1OTY4MzF9.8MCwZM1tSoXTtVeg1hjEXYrNQKd4ciXq2zQuVuwpyLg


### list all orders
GET http://localhost:3000/api/v1/orders

### Add a new order
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
  "customer_id": 6,
  "orderDate": "2021-05-01",
  "price": 21.98
}

### Get an order by id
GET http://localhost:3000/api/v1/orders/2

### Update an order
PUT http://localhost:3000/api/v1/orders/2
Content-Type: application/json

{
  "customer_id": 6,
  "orderDate": "2022-05-02",
  "price": 22.98
}


### Delete an order
DELETE http://localhost:3000/api/v1/orders/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo1LCJuYW1lIjoiYWRtaW4iLCJhZGRyZXNzIjoibm9uZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzNTEwNDMxLCJleHAiOjE3MTM1OTY4MzF9.8MCwZM1tSoXTtVeg1hjEXYrNQKd4ciXq2zQuVuwpyLg




### list all shopping carts
GET http://localhost:3000/api/v1/shoppingcarts

### Add a new shopping cart
POST http://localhost:3000/api/v1/shoppingcarts
Content-Type: application/json

{
  "orderId": 3,
  "productId": 9,
  "quantity": 2
}

### Get a shopping cart by id
GET http://localhost:3000/api/v1/shoppingcarts/4

### Update a shopping cart
PUT http://localhost:3000/api/v1/shoppingcarts/4
Content-Type: application/json

{
  "orderId": 3,
  "productId": 9,
  "quantity": 5
}

### Delete a shopping cart
DELETE http://localhost:3000/api/v1/shoppingcarts/1


### Register a new user
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "test",
  "address": "Myllypuro",
  "email": "test@metropolia.fi",
  "password": "123",
  "role": "user"
}


### Get all categories
GET http://localhost:3000/api/v1/categories

### Add a new category
POST http://localhost:3000/api/v1/categories
Content-Type: application/json

{
  "name": "Test Category"
}

### Get a category by id
GET http://localhost:3000/api/v1/categories/1

### Update a category
PUT http://localhost:3000/api/v1/categories/1
Content-Type: application/json

{
  "name": "Test Category Updated",
  "description": "This is a test category updated"
}

### Delete a category
DELETE http://localhost:3000/api/v1/categories/1

### List all reviews
GET http://localhost:3000/api/v1/reviews


### Add a new review
POST http://localhost:3000/api/v1/reviews
Content-Type: application/json

{
  "customerId": 6,
  "orderId": 3,
  "rating": 3
}

### Get a review by id
GET http://localhost:3000/api/v1/reviews/1

### Update a review
PUT http://localhost:3000/api/v1/reviews/1
Content-Type: application/json

{
  "customerId": 6,
  "orderId": 3,
  "rating": 2
}

### Delete a review
DELETE http://localhost:3000/api/v1/reviews/2
