### Add a new product
POST http://localhost:3000/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxMSwibmFtZSI6InBhdHJpa2h5IiwiYWRkcmVzcyI6Im5vbmUiLCJlbWFpbCI6InBhdHJpay5oeXl0aWFpbmVuQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDExNzc3Mn0.QimAUQWUmjt5Km5zidY72-lCeY5Wx4Y-zttWr4tqKZg
Content-Type: application/json

{
  "name": "Test Food",
  "description": "This is a test food",
  "price": 19.99,
  "image": "test.jpg",
  "categoryId": 1
}

### List all products
GET http://localhost:3000/api/v1/products

### Get a product by id
GET http://localhost:3000/api/v1/products/11

### Update a product
PUT http://localhost:3000/api/v1/products/2
Content-Type: application/json

{
  "name": "Frozen foods",
  "description": "This is a test food updated",
  "price": 20.99,
  "category": "Test Category Updated",
  "image": "testUpdate.jpg"
}

### Delete a product
DELETE http://localhost:3000/api/v1/products/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxMSwibmFtZSI6InBhdHJpa2h5IiwiYWRkcmVzcyI6Im5vbmUiLCJlbWFpbCI6InBhdHJpay5oeXl0aWFpbmVuQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDExNzc3Mn0.QimAUQWUmjt5Km5zidY72-lCeY5Wx4Y-zttWr4tqKZg





### Add a new customer
POST http://localhost:3000/api/v1/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxMSwibmFtZSI6InBhdHJpa2h5IiwiYWRkcmVzcyI6Im5vbmUiLCJlbWFpbCI6InBhdHJpay5oeXl0aWFpbmVuQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDExNzc3Mn0.QimAUQWUmjt5Km5zidY72-lCeY5Wx4Y-zttWr4tqKZg
Content-Type: application/json

{
  "name": "PatrikHh",
  "address": "none",
  "email": "patrik.hyytiainen@gmail.com",
  "password": "patrik123",
  "role": "admin"
}

### Register a new customer
POST http://10.120.32.54/app/api/v1/auth/register
Content-Type: application/json

{
  "name": "PatrikH",
  "address": "Helsinki katu 2",
  "email": "gfds@gmail.com",
  "password": "123",
  "role": "admin"
}
### Login
POST http://10.120.32.54/app/api/v1/auth/login
Content-Type: application/json

{
  "name": "PatrikH",
  "password": "123"
}

### Login local
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "name": "patrikhy",
  "password": "patrik123"
}

### List all customers
GET http://localhost:3000/api/v1/customers


### Get a customer by id
GET http://localhost:3000/api/v1/customers/1

### Modify a customer
PUT http://10.120.32.54/app/api/v1/customers/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxNiwibmFtZSI6InBldHRlcmlwdW5ha3Vvbm8iLCJhZGRyZXNzIjoiSGVsc2lua2kga2F0dSAyIiwiZW1haWwiOiJ0ZXN0YWRzZkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNDQ4NTM4N30.0yNEl8y9woi9MgYdPYPDsme3Tb5O6QdcmHME3KQmoPo
Content-Type: application/json

{
  "name": "petteripunakuono",
  "address": "Helsinki katu 6",
  "email": "patrik@gmail.com",
  "password": "123",
}

### Delete a customer
DELETE http://localhost:3000/api/v1/customers/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxMSwibmFtZSI6InBhdHJpa2h5IiwiYWRkcmVzcyI6Im5vbmUiLCJlbWFpbCI6InBhdHJpay5oeXl0aWFpbmVuQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDExNzc3Mn0.QimAUQWUmjt5Km5zidY72-lCeY5Wx4Y-zttWr4tqKZg


### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxOCwibmFtZSI6InRlc3RpIiwiYWRkcmVzcyI6Im5vbmUiLCJlbWFpbCI6InRlc3RpLmh5eXRpYWluZW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE0MTI0Nzc1fQ.0P0tQvjT8aesG7BTnG_Xu0iIWRMJVU5LyB4zfI57YJM

### list all orders
GET http://localhost:3000/api/v1/orders

### Add a new order
POST http://10.120.32.54/app/api/v1/orders
Content-Type: application/json

{
  "customerId": 11,
  "orderDate": "2024-05-07",
  "price": 55,
  "status_code": 0
}

### Modify order
PUT http://10.120.32.54/app/api/v1/orders/21
Content-Type: application/json

{
  "customer_id": 11,
  "orderDate": "2021-05-01",
  "price": 21.98,
  "status_code": 0
}

### Get an order by id
GET http://localhost:3000/api/v1/orders/21

### Update an order
PUT http://localhost:3000/api/v1/orders/2
Content-Type: application/json

{
  "customer_id": 6,
  "orderDate": "2022-05-02",
  "price": 22.98
}


### Delete an order
DELETE http://localhost:3000/api/v1/orders/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxMSwibmFtZSI6InBhdHJpa2h5IiwiYWRkcmVzcyI6Im5vbmUiLCJlbWFpbCI6InBhdHJpay5oeXl0aWFpbmVuQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDExNzc3Mn0.QimAUQWUmjt5Km5zidY72-lCeY5Wx4Y-zttWr4tqKZg




### list all shopping carts
GET http://localhost:3000/api/v1/shoppingcarts

### Add a new shopping cart
POST http://localhost:3000/api/v1/shoppingcarts
Content-Type: application/json

{
  "orderId": 22,
  "productId": 11,
  "quantity": 2
}

### Get a shopping cart by id
GET http://localhost:3000/api/v1/shoppingcarts/4

### Update a shopping cart
PUT http://localhost:3000/api/v1/shoppingcarts/4
Content-Type: application/json

{
  "orderId": 3,
  "productId": 9,
  "quantity": 5
}

### Create a new orderItem
POST http://localhost:3000/api/v1/orderitems
Content-Type: application/json

{
  "orderId": 22,
  "productId": 11,
  "quantity": 2
}

### Delete a shopping cart
DELETE http://localhost:3000/api/v1/shoppingcarts/1


### Register a new user
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "test",
  "address": "Myllypuro",
  "email": "test@metropolia.fi",
  "password": "123",
  "role": "user"
}


### Get all categories
GET http://localhost:3000/api/v1/categories

### Add a new category
POST http://localhost:3000/api/v1/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxMSwibmFtZSI6InBhdHJpa2h5IiwiYWRkcmVzcyI6Im5vbmUiLCJlbWFpbCI6InBhdHJpay5oeXl0aWFpbmVuQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDExNzc3Mn0.QimAUQWUmjt5Km5zidY72-lCeY5Wx4Y-zttWr4tqKZg

{
  "name": "Salty products"
}

### Get a category by id
GET http://localhost:3000/api/v1/categories/1

### Update a category
PUT http://localhost:3000/api/v1/categories/1
Content-Type: application/json

{
  "name": "Test Category Updated",
  "description": "This is a test category updated"
}

### Delete a category
DELETE http://localhost:3000/api/v1/categories/1

### List all reviews
GET http://localhost:3000/api/v1/reviews


### Add a new review
POST http://localhost:3000/api/v1/reviews
Content-Type: application/json

{
  "customerId": 6,
  "orderId": 3,
  "rating": 3
}

### Get a review by id
GET http://localhost:3000/api/v1/reviews/1

### Update a review
PUT http://localhost:3000/api/v1/reviews/1
Content-Type: application/json

{
  "customerId": 6,
  "orderId": 3,
  "rating": 2
}

### Delete a review
DELETE http://localhost:3000/api/v1/reviews/2
