### Add a new product
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Test Food",
  "description": "This is a test food",
  "price": 10.99,
  "category": "Test Category",
  "image": "test.jpg"
}

### List all products
GET http://localhost:3000/api/v1/products

### Get a product by id
GET http://localhost:3000/api/v1/products/2

### Update a product
PUT http://localhost:3000/api/v1/products/2
Content-Type: application/json

{
  "name": "Test Food Updated",
  "description": "This is a test food updated",
  "price": 20.99,
  "category": "Test Category Updated",
  "image": "testUpdate.jpg"
}

### Delete a product
DELETE http://localhost:3000/api/v1/products/2




### Add a new customer
POST http://localhost:3000/api/v1/customers
Content-Type: application/json

{
  "name": "Patrik",
  "address": "Espoo katu",
  "email": "patrik@gmail.com",
  "password": "123",
  "role": "user"
}

### List all customers
GET http://localhost:3000/api/v1/customers


### Get a customer by id
GET http://localhost:3000/api/v1/customers/1

### Modify a customer
PUT http://localhost:3000/api/v1/customers/1
Content-Type: application/json

{
  "name": "Urpo",
  "address": "Helsinki katu 2",
  "email": "dunno@gmail.com",
  "password": "password",
  "role": "user"
}

### Delete a customer
DELETE http://localhost:3000/api/v1/customers/1


### Post login
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "name": "Patrik",
  "password": "123"
}

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjozLCJuYW1lIjoiUGF0cmlrIiwiYWRkcmVzcyI6IkVzcG9vIGthdHUiLCJlbWFpbCI6InBhdHJpa0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMzQzOTAwNSwiZXhwIjoxNzEzNTI1NDA1fQ.DuoCFtac9XAZIz8kU4HIY2Yggc-IbDs6tpMcg38GtJQ


### list all orders
GET http://localhost:3000/api/v1/orders

### Add a new order
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
  "customer_id": 1,
  "orderDate": "2021-05-01",
  "price": 21.98
}

### Get an order by id
GET http://localhost:3000/api/v1/orders/1

### Update an order
PUT http://localhost:3000/api/v1/orders/8
Content-Type: application/json

{
  "customer_id": 1,
  "orderDate": "2022-05-02",
  "price": 22.98
}


### Delete an order
DELETE http://localhost:3000/api/v1/orders/8



### list all shopping carts
GET http://localhost:3000/api/v1/shoppingcarts

### Add a new shopping cart
POST http://localhost:3000/api/v1/shoppingcarts
Content-Type: application/json

{
  "orderId": 1,
  "productId": 3,
  "quantity": 2
}

### Get a shopping cart by id
GET http://localhost:3000/api/v1/shoppingcarts/1

### Update a shopping cart
PUT http://localhost:3000/api/v1/shoppingcarts/1
Content-Type: application/json

{
  "order_id": 1,
  "product_id": 1,
  "quantity": 3
}

### Delete a shopping cart
DELETE http://localhost:3000/api/v1/shoppingcarts/1
